version: '2'

services:
  server:
    environment:
      - CLIENT_EMAIL = ${CLIENT_EMAIL}
      - CLIENT_ID = ${CLIENT_ID}
      - PRIVATE_KEY = ${PRIVATE_KEY}
      - PRIVATE_KEY_ID = ${PRIVATE_KEY_ID}
      - PROJECT_ID = ${PROJECT_ID}
    image: 'springboot-docker-compose-app:latest'
    build:
      context: .
    container_name: hookah-backend
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: 'postgres:14.5-alpine3.16'
    container_name: hookah-db-dev
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=hoookah
      - POSTGRES_PASSWORD=123456