name: 'Checkout project & make Docker image & push'
on:
  push:
    branches:
      - 'hoxfix/actions-deploy-fix'
    #tags:
    #  - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dockerwell/hookaorder-backend:wip
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    if: ${{ success() }}
    steps:
    - name: Checkout deploy config
      uses: actions/checkout@v3
    - name: Deploy to Docker Host
      run: PRKEY=`${{ secrets.DOCKER_SSH_PRIVATE_KEY }}` PBKEY=`${{ secrets.DOCKER_SSH_PUBLIC_KEY }}` REF=`wip` ./github/scripts/deploy.sh
