name: 'Checkout project & make Docker image & push'

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    environment: hookahorder
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dockerwell/hookaorder-backend:${{  github.ref_name }}
          # Тут указываем переменные, которые нужно передать в окружение в контейнер
          build-args: |
            CLIENT_EMAIL= ${{ vars.CLIENT_EMAIL }}
            CLIENT_ID= ${{ vars.CLIENT_ID }}
            PRIVATE_KEY= ${{ vars.PRIVATE_KEY }}
            PRIVATE_KEY_ID= ${{ vars.PRIVATE_KEY_ID }}
            PROJECT_ID:= ${{ vars.PROJECT_ID }}