name: 'Checkout project & make Docker image & push'
on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dockerwell/hookaorder-backend:${{  github.ref_name }}
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    if: ${{ success() }}
    steps:
      - name: "Trigger jenkins job"
        uses: GoldenspearLLC/build-jenkins-job@master
        with:
          jenkins-url: "http://http://95.163.242.79:8081"
          jenkins-token: "11ba1b2e0d8f1085cf1726a5884b64d669"
          user: "deployer"
          job-path: "job/Backend/job/JavaBackEnd"
          job-params: "{'JBTAG': '${{  github.ref_name }}'}"
      - name: Get job status
        run: echo "Job status is ${{ steps.job-build.outputs.job_status }}"
