name: 'Checkout project & make Docker image & push'
on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dockerwell/hookaorder-backend:${{  github.ref_name }}
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    if: ${{ success() }}
    steps:
    - name: Deploy to Docker Host
      run: |
        echo "Registering SSH keys..."
        mkdir -p ~/.ssh
        printf '%s\n' ${{ secrets.DOCKER_SSH_PRIVATE_KEY }} > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        printf '%s\n' ${{ secrets.DOCKER_SSH_PUBLIC_KEY }} > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa.pub
        eval $(ssh-agent)
        ssh-add ~/.ssh/id_rsa
        echo "Add known hosts"
        printf '%s %s\n' "95.163.242.79" "${{ secrets.DOCKER_SSH_PUBLIC_KEY }}" > /etc/ssh/ssh_known_hosts
        ssh deployer@95.163.242.79 "JBTAG=${{ github.ref_name }} docker compose -f /opt/staging/docker-compose.yaml up -d java-backend"
