name: 'Checkout project & make Docker image & push'
on:
  push:
    tags:
      - '*'

jobs:
  docker:
    environment: hookaorder
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "credentials.json"
          json: ${{ secrets.HOOKAH_FIREBASE }}
          dir: 'src/main/resources'
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: dockerwell/hookaorder-backend:${{  github.ref_name }}