name: 'Checkout project & make Docker image & push'
on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: hookaorder
    steps:
#      - name: Set up QEMU
      #        uses: docker/setup-qemu-action@v2
      #      - name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v2
      #      - name: Login to Docker Hub
      #        uses: docker/login-action@v2
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "service-account.json"
          json: ${{ secrets.SERVICE }}
          dir: 'src/main/resources/'
      - name: create ENV file
        uses: schdck/create-env-json@v1
        id: create-env
        with:
          file-name: 'env.json'
          CLIENT_EMAIL: ${{ vars.CLIENT_EMAIL }}
          CLIENT_ID: ${{ vars.CLIENT_ID }}
          PRIVATE_KEY: ${{ vars.PRIVATE_KEY }}
          PRIVATE_KEY_ID: ${{ vars.PRIVATE_KEY_ID }}
          PROJECT_ID: ${{ vars.PROJECT_ID }}
      - name: Build and push
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose.yaml"