name: 'Checkout project & make Docker image & push'
on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dockerwell/hookaorder-backend:${{  github.ref_name }}
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Docker Host
      uses: wshihadeh/docker-deployment-action@v2
      with:
        remote_docker_host: deployer@95.163.242.79
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        deployment_mode: docker-compose
        args: up -d java-backend
        docker_prune: 'true'
        pull_images_first: 'true'
        pre_deployment_command_args: JBV=${{  github.ref_name }} INPUT_STACK_FILE_NAME=/opt/staging/docker-compose.yaml
